//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductEFMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
       
        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "Please Enter Product Name")]
        public string ProductName { get; set; }
        
        [Display(Name = "Product Price")]
        [Required(ErrorMessage = "Please Enter Product Price")]
        public int ProductPrice { get; set; }
        
        [Display(Name = "SL.No")]
        [Required(ErrorMessage = "Please Enter SL.No")]
        public int Slno { get; set; }
    }
}
